### ISSUE TITLE
Projects as data

### ISSUE THREAD

**Issue by StevenBlack** [VFPX/VFPX.github.io#1]
Currently [projects.md](https://github.com/VFPX/VFPX.github.io/blob/master/projects.md) is an html table.

In Jekyll this is trivial to [implement from data](https://jekyllrb.com/docs/datafiles/) with the added benefit that all references can be localized in one place.  I recommend a json structure for this.

@DougHennig does the project list exist as a data structure?  Otherwise parsing the html is required.

**Comment by DougHennig** [comment]
No, it doesn't exist as a data structure but I agree it should, as it'll be way easier to maintain. What do you recommend?

**Comment by StevenBlack** [comment]
I'm thinking a new `/_data` folder with `projects.json` file, then mod `projects.md` to spin `site.data.projects`.

I'll submit a pull request.  

- [x] Create `/_data/projects.json`
- [x] Adapt [projects.md](https://github.com/VFPX/VFPX.github.io/blob/master/projects.md) to generate from data.

**Comment by DougHennig** [comment]
Thanks for the groundwork. I've rewritten projects.md to read from the data and added a NonVFPX.json file for those projects.
