### ISSUE TITLE
Where is the `page` layout

### ISSUE THREAD

**Issue by StevenBlack** [VFPX/VFPX.github.io#5]
Something appears to be missing.

Most (all?) pages have `layout: page` in the front-matter, yet I can't see a file named `page` in the `_layouts` folder.

**Background**: I notice that most pages within vfpx.github.io double-up the page title – for example https://vfpx.github.io/projects/ and most others – but I can't fix it 😄

**Comment by DougHennig** [comment]
That was a copy and paste issue. Fixed (which also fixed the doubling of the page title).
